version: '3.8'

services:
  list-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./lists.db:/app/lists.db
    restart: unless-stopped
